[workspace]
channels = ["conda-forge"]
name = "mothman"
platforms = ["osx-64", "linux-64"]
version = "0.1.0"

[tasks]

[dependencies]
numpy = ">=2.3.2,<3"
matplotlib = ">=3.10.5,<4"
ipykernel = ">=6.30.1,<7"
pandas = ">=2.3.2,<3"
scipy = ">=1.16.3,<2"
